# Generated by Django 3.2.8 on 2021-11-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('img', models.ImageField(upload_to='images/')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categorie',
            },
        ),
    ]
