# Generated by Django 3.1.3 on 2022-02-06 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBakerys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('img', models.ImageField(upload_to='images/')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CategorieBakerys',
            },
        ),
        migrations.CreateModel(
            name='CustomerBakerys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemBakerys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itm_id', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('prix', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=150)),
                ('img', models.ImageField(upload_to='images/')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakerys.categorybakerys')),
            ],
        ),
        migrations.CreateModel(
            name='ItemChoiceCategoryBakerys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bakerys.itembakerys')),
            ],
        ),
        migrations.CreateModel(
            name='IventoryItemCategoryBakerys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBakerys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=20, null=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('table', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, max_length=50)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bakerys.customerbakerys')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemBakerys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('ingredient', models.CharField(blank=True, max_length=150, null=True)),
                ('seasoning', models.CharField(blank=True, max_length=150, null=True)),
                ('cuisson', models.CharField(blank=True, max_length=150, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bakerys.customerbakerys')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bakerys.itembakerys')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bakerys.orderbakerys')),
            ],
        ),
        migrations.CreateModel(
            name='IventoryItemBakerys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('prix', models.IntegerField(blank=True)),
                ('quantity', models.IntegerField(blank=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bakerys.iventoryitemcategorybakerys')),
            ],
        ),
        migrations.CreateModel(
            name='ItemChoicesBakerys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True, max_length=20)),
                ('prix', models.IntegerField(blank=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('choice_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bakerys.itemchoicecategorybakerys')),
                ('parent_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bakerys.itembakerys')),
            ],
        ),
    ]
