# Generated by Django 3.1.3 on 2022-02-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakerys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybakerys',
            name='img',
            field=models.ImageField(upload_to='images/Bakerys'),
        ),
        migrations.AlterField(
            model_name='itembakerys',
            name='img',
            field=models.ImageField(upload_to='images/Bakerys'),
        ),
    ]
