# Generated by Django 3.2.8 on 2021-11-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bakerys', '0003_rename_customerbakerys_customerbekerys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='ItemBakerys',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderBakerys',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderItemBakerys',
        ),
    ]
