# Generated by Django 3.2.8 on 2021-11-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakerys', '0004_auto_20211111_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbakerys',
            name='note',
            field=models.TextField(default=100),
        ),
        migrations.AddField(
            model_name='orderbakerys',
            name='table',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
