# Generated by Django 3.2.8 on 2021-11-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakerys', '0005_auto_20211123_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbakerys',
            name='table',
            field=models.IntegerField(default=1),
        ),
    ]
