# Generated by Django 3.2.8 on 2021-11-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakerys', '0006_alter_orderbakerys_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbakerys',
            name='note',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
