# Generated by Django 3.2.8 on 2021-12-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakerys', '0007_alter_orderbakerys_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbakerys',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
