# Generated by Django 3.1.3 on 2021-12-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakerys', '0008_alter_orderbakerys_transaction_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerbekerys',
            options={'verbose_name': 'CustomerBekery'},
        ),
        migrations.AlterModelOptions(
            name='itembakerys',
            options={'verbose_name': 'ItemBakery'},
        ),
        migrations.AlterModelOptions(
            name='orderbakerys',
            options={'verbose_name': 'OrderBakery'},
        ),
        migrations.AlterModelOptions(
            name='orderitembakerys',
            options={'verbose_name': 'OrderItemBakery'},
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customerbekerys',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itembakerys',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderbakerys',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderitembakerys',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
