# Generated by Django 3.1.3 on 2022-02-07 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='phone',
        ),
    ]
