# Generated by Django 3.1.3 on 2022-04-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='accompagnement',
        ),
        migrations.DeleteModel(
            name='Accompagnement',
        ),
    ]
