# Generated by Django 3.1.3 on 2022-03-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0002_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default=1, max_length=10, null=True),
        ),
    ]
