# Generated by Django 3.1.3 on 2022-04-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0002_auto_20220422_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accompagnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('prix', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='accompagnement',
            field=models.ManyToManyField(blank=True, to='Resto.Accompagnement'),
        ),
    ]
