# Generated by Django 3.1.3 on 2022-04-03 19:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0003_auto_20220311_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[500, 300], upload_to='images/'),
        ),
    ]
