# Generated by Django 4.0.4 on 2022-05-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0004_remove_order_note_remove_orderitem_cuisson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='accompagnememt',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='accompagnememt',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
