# Generated by Django 3.1.3 on 2022-04-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0004_auto_20220403_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
