# Generated by Django 4.0.5 on 2022-06-28 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0005_remove_orderitem_accompagnememt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('amount', models.CharField(blank=True, max_length=150)),
                ('currency', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('operator_id', models.CharField(blank=True, max_length=150)),
                ('payment_date', models.CharField(blank=True, max_length=150)),
                ('payment_method', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(blank=True, max_length=150)),
                ('transactionID', models.CharField(blank=True, max_length=150, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resto.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
