# Generated by Django 4.0.5 on 2022-07-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0006_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='accompagnement',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='accompagnememt',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='accompagnememt',
            field=models.ManyToManyField(blank=True, max_length=150, to='Resto.accompagnement'),
        ),
    ]
