# Generated by Django 4.0.5 on 2022-07-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0007_accompagnement_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='accompagnememt',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='accompagnememt',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
