# Generated by Django 4.0.5 on 2022-07-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0008_remove_orderitem_accompagnememt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='accompagnememt',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='accompagnememt',
            field=models.ManyToManyField(to='Resto.accompagnement'),
        ),
    ]
