# Generated by Django 4.0.5 on 2022-08-05 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0008_remove_orderitem_accompagnememt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='accompagnememt',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='accompagnememt',
            field=models.ManyToManyField(blank=True, to='Resto.accompagnement'),
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('prix', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('img', models.ImageField(blank=True, upload_to='images/')),
                ('item', models.ManyToManyField(blank=True, to='Resto.item')),
            ],
        ),
        migrations.CreateModel(
            name='SideOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(blank=True, upload_to='images/')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resto.customer')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resto.accompagnement')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Resto.order')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='supplement',
            field=models.ManyToManyField(blank=True, to='Resto.supplement'),
        ),
    ]
