# Generated by Django 4.0.5 on 2022-08-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0009_remove_orderitem_accompagnememt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accompagnement',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
