# Generated by Django 3.1.14 on 2022-07-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0009_auto_20220720_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='accompagnememt',
            field=models.ManyToManyField(blank=True, to='Resto.Accompagnement'),
        ),
    ]
