# Generated by Django 3.2.15 on 2022-08-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0010_accompagnement_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemchoices',
            name='parent_food',
        ),
        migrations.AddField(
            model_name='itemchoices',
            name='parent_food',
            field=models.ManyToManyField(blank=True, to='Resto.Item'),
        ),
    ]
