# Generated by Django 4.0.5 on 2022-08-01 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0010_alter_orderitem_accompagnememt'),
        ('Resto', '0010_auto_20220720_1541'),
    ]

    operations = [
    ]
