# Generated by Django 3.2.15 on 2022-08-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0011_auto_20220825_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemchoicecategory',
            name='item',
        ),
        migrations.AddField(
            model_name='itemchoicecategory',
            name='item',
            field=models.ManyToManyField(blank=True, to='Resto.Item'),
        ),
    ]
