# Generated by Django 4.0.5 on 2022-08-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0012_alter_accompagnement_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accompagnement',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='sideorderitem',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Complement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('prix', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('img', models.ImageField(blank=True, upload_to='images/')),
                ('item', models.ManyToManyField(blank=True, to='Resto.item')),
            ],
        ),
    ]
