# Generated by Django 3.2.15 on 2022-08-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0012_auto_20220825_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchoicecategory',
            name='multiple_choice',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
