# Generated by Django 4.0.5 on 2022-08-02 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0013_accompagnement_img_sideorderitem_img_complement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complement',
            new_name='Supplement',
        ),
    ]
