# Generated by Django 3.2.8 on 2021-11-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0013_alter_orderitem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
