# Generated by Django 3.2.15 on 2022-08-29 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0013_itemchoicecategory_multiple_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='itm_id',
        ),
    ]
