# Generated by Django 4.0.5 on 2022-08-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0014_rename_complement_supplement'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='supplement',
            field=models.ManyToManyField(blank=True, to='Resto.supplement'),
        ),
    ]
