# Generated by Django 3.2.15 on 2022-08-30 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0014_remove_item_itm_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_id',
        ),
    ]
