# Generated by Django 3.2.8 on 2021-11-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0015_auto_20211104_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='prix',
            field=models.IntegerField(),
        ),
    ]
