# Generated by Django 3.2.15 on 2022-08-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0015_remove_category_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompagnement',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
