# Generated by Django 3.2.8 on 2021-11-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0016_alter_item_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.IntegerField(default=1),
        ),
    ]
