# Generated by Django 3.2.15 on 2022-09-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0016_alter_accompagnement_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemchoicecategory',
            name='item',
        ),
    ]
