# Generated by Django 3.2.15 on 2022-09-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0017_remove_itemchoicecategory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchoicecategory',
            name='item',
            field=models.ManyToManyField(blank=True, to='Resto.Item'),
        ),
    ]
