# Generated by Django 3.1.3 on 2021-12-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0018_auto_20211214_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
