# Generated by Django 3.2.15 on 2022-09-07 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0018_itemchoicecategory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Resto.order'),
            preserve_default=False,
        ),
    ]
