# Generated by Django 3.1.3 on 2021-12-21 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0019_auto_20211217_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accompagment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=150)),
                ('prix', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('parent_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resto.item')),
            ],
        ),
    ]
