# Generated by Django 3.2.15 on 2022-09-07 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0019_transactions_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemchoicecategory',
            name='item',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='order',
        ),
    ]
