# Generated by Django 3.2.15 on 2022-09-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0020_auto_20220906_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchoicecategory',
            name='item',
            field=models.ManyToManyField(blank=True, to='Resto.Item'),
        ),
    ]
