# Generated by Django 3.1.3 on 2021-12-22 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0020_accompagment_supplement'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='assaisonement',
            field=models.CharField(blank=True, choices=[('Avec Piment', 'Avec Piment'), ('Sans Piment', 'Sans Piment')], max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='boisson_choice',
            field=models.CharField(blank=True, choices=[('Coca-Cola', 'Coca-Cola'), ('Fanta', 'Fanta'), ('Sprite', 'Sprite')], max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='steak_choice',
            field=models.CharField(blank=True, choices=[('Rare', 'Rare'), ('Medium', 'Medium'), ('Medium Rare', 'Medium Rare'), ('Medium Well', 'Medium Well'), ('Well Done', 'Well Done')], max_length=50),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='parent_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resto.item'),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='prix',
            field=models.IntegerField(blank=True),
        ),
    ]
