# Generated by Django 3.1.3 on 2021-12-22 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0021_auto_20211221_2208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplement',
            new_name='ItemChoices',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resto.itemchoices'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resto.item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Resto.order'),
        ),
    ]
