# Generated by Django 3.2.15 on 2022-09-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0021_itemchoicecategory_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ingredient',
            field=models.ManyToManyField(blank=True, to='Resto.ItemChoices'),
        ),
    ]
