# Generated by Django 3.1.3 on 2021-12-24 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0022_auto_20211222_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemChoiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='assaisonement',
        ),
        migrations.RemoveField(
            model_name='item',
            name='boisson_choice',
        ),
        migrations.RemoveField(
            model_name='item',
            name='steak_choice',
        ),
        migrations.AlterField(
            model_name='itemchoices',
            name='description',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='itemchoices',
            name='choice_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resto.itemchoicecategory'),
        ),
    ]
