# Generated by Django 3.1.3 on 2021-12-25 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0023_auto_20211224_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchoicecategory',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resto.item'),
        ),
    ]
