# Generated by Django 3.1.3 on 2021-12-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0024_itemchoicecategory_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_choice',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cuisson',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ingredient',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seasoning',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
