# Generated by Django 3.1.3 on 2022-01-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0026_auto_20211228_1039'),
        ('Resto', '0026_iventoryitem_iventoryitemcategory_myuser'),
    ]

    operations = [
    ]
