# Generated by Django 4.0 on 2022-01-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0027_merge_20220104_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iventoryitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='iventoryitemcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
